# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fe82ee37290b65ca3c9619bdbcd5b0df06f24731e88dd6f0c4cf4daa7b197b522646cddeacec929a6d73210418cd05d48aa398b2fa9505adc225d91f1fa1d7e

test:
  secret_key_base: 4ea2478baa29cd470adccd26c416fbf34d99f582e347d88aa3ccc019e3e1396c84a62e86aa151726e5b81f6967eebf292b57dbf38263d46530a16b697295fa87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
